mots = {
    # Noms communs courants
    "Thé": "Café",
    "Chaussure": "Lacets",
    "Table": "Chaise",
    "Livre": "Marque-page",
    "Baguette": "Croissant",
    "Orage": "Pluie",
    "Clé": "Serrure",
    "Ordinateur": "Clavier",
    "Crayon": "Stylo",
    "Bateau": "Navire",
    "Télévision": "Écran",
    "Sel": "Sucre",
    "Journal": "Magazine",
    "Chat": "Chaton",
    "Porte": "Portail",
    "Lune": "Soleil",
    "Montagne": "Colline",
    "Pizza": "Quiche",
    "Tasse": "Verre",
    "Tablette": "Ordinateur",
    "Armoire": "Commode",
    "Vélo": "Trottinette",
    "Chaise": "Tabouret",
    "Couteau": "Fourchette",
    "Lit": "Canapé",
    "Veste": "Manteau",
    "Magazine": "Livre",
    "Téléphone": "Smartphone",
    
    # Marques
    "Nike": "Adidas",
    "Apple": "Samsung",
    "Coca-Cola": "Pepsi",
    "McDonald's": "Burger King",
    "Starbucks": "Costa",
    "Sony": "Panasonic",
    "Toyota": "Honda",
    "Ford": "Chevrolet",
    "PlayStation": "Xbox",
    "Lego": "Playmobil",
    
    # Personnages de fiction
    
    "Batman": "Robin",
    "Mario": "Luigi",
    "Dr. Watson": "Sherlock Holmes",
    "Dobby": "Hedwige",
    "Frodo": "Sam",
    "Spider-Man": "Venom",
    "Winnie": "Porcinet",
    "Iron Man": "Batman",
    "Superman": "Spiderman",
    "Nintendo": "PlayStation",
    "Star Wars": "Star Trek",
    "Fanta": "Coca-Cola",
    "Harry Potter": "Hermione Granger",
    "Mickey": "Donald",
    "Sherlock Holmes": "Hercule Poirot",
    "Pikachu": "Dracofeu",
    "Dirty Dancing": "Grease",
    "Gandalf": "Dumbledore",
    "Lara Croft": "Nathan Drake",
    "Thor": "Loki",
    "Dark Vador": "Luke Skywalker",
    "R2-D2": "Luke Skywalker",
    "Tom": "Jerry",
    "Woody": "Buzz Lightyear",
    
    # Divers (villes, artistes, etc...)
    "Quentin Tarantino": "Christopher Nolan",
    "Steven Spielberg": "James Cameron",
    "Brad Pitt": "Leonardo DiCaprio",
    "Johnny Depp": "Orlando Bloom",
    "Meryl Streep": "Anne Hathaway",
    "Avatar": "La Planète des Singes",
    "La La Land": "Barbie",
    "Matrix": "Inception",
    "Jurassic Park": "King Kong",
    "Paris": "Lyon",
    "New York": "Los Angeles",
    "Marilyn Monroe": "Audrey Hepburn",
    "Titanic": "Atlantide",
    "Mozart": "Beethoven",
    "Einstein": "Newton",
    "Bach": "Vivaldi",
    "Forêt": "Jungle",
    "Rome": "Athènes",
    "Berlin": "Vienne",
    "Hollywood": "Broadway",
    "James Bond": "Tom Cruise",
    "Walt Disney": "Steven Spielberg",
    "Tesla": "Edison",
    "Lincoln": "Washington",
    "Renaissance": "Baroque",
    "Louvre": "Musée d'Orsay",
    
    # Nature
    "Arbre": "Forêt",
    "Rivière": "Lac",
    "Montagne": "Vallée",
    "Soleil": "Lune",
    "Océan": "Mer",
    "Fleur": "Bouquet",
    "Neige": "Glace",
    "Plage": "Dune",
    "Volcan": "Lave",
    "Ciel": "Nuage",
    
    # Artistes
    "Vincent van Gogh": "Claude Monet",
    "Pablo Picasso": "Salvador Dalí",
    "Léonard de Vinci": "Michel-Ange",
    "Mozart": "Beethoven",
    "Frida Kahlo": "Georgia O'Keeffe",
    "Andy Warhol": "Jean-Michel Basquiat",
    "Bob Dylan": "Leonard Cohen",
    "David Bowie": "Freddie Mercury",
    "Beyoncé": "Rihanna",
    "Elton John": "Billy Joel",
    
    # Sport
    "Football": "Basketball",
    "Tennis": "Badminton",
    "Cristiano Ronaldo": "Lionel Messi",
    "Michael Jordan": "LeBron James",
    "Serena Williams": "Maria Sharapova",
    "Tour de France": "Giro d'Italia",
    "Formule 1": "MotoGP",
    "Boxe": "MMA",
    "Rugby": "Football Américain",
    "Padel": "Tennis de table",
    
    # Histoire et culture G
    "Albert Einstein": "Isaac Newton",
    "Napoléon": "Jules César",
    "Cléopâtre": "Néfertiti",
    "Marie Curie": "Rosalind Franklin",
    "Winston Churchill": "Franklin D. Roosevelt",
    "Charles de Gaulle": "Winston Churchill",
    "Martin Luther King": "Malcolm X",
    "Nelson Mandela": "Gandhi",
    "Joan of Arc": "Catherine de Médicis",
    "Léonard de Vinci": "Galilée",
    "Platon": "Aristote",
    "Sahara": "Gobi",
    "Amazone": "Nile",
    "Big Bang": "Théorie de l'évolution",
    "Oxygène": "Azote",
    "Anubis": "Osiris",
    "Renaissance": "Moyen Âge",
    "Archimède": "Euclide",
    "Fibonacci": "Pythagore",
    "Versailles": "Chambord",
    "Farfadet": "Chenapant"
}
